"""Generate the cue illustration figures and their measured values.

Run from anywhere:  python3 tools/gen_figures.py   (needs numpy + Pillow)
Writes  assets/figures/generated/*  and  assets/data/cue_examples.js

The edge maps use a simple edge filter for illustration (AC-MOT itself uses
OpenCV Canny(50,120)). Mean gray and Laplacian variance are computed on the
quarter-scale grayscale image exactly as the Scene Analyzer does.
"""
import json, os
import numpy as np
from PIL import Image, ImageFile, ImageFilter

ImageFile.LOAD_TRUNCATED_IMAGES = True
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FIG = os.path.join(ROOT, "assets", "figures")
OUT = os.path.join(FIG, "generated")
os.makedirs(OUT, exist_ok=True)


def quarter(name):
    im = Image.open(os.path.join(FIG, name)).convert("RGB")
    w, h = im.size
    small = im.resize((max(1, w // 4), max(1, h // 4)), Image.BILINEAR)
    return small, small.convert("L")


def lap_var(gray):
    a = np.asarray(gray, dtype=np.float64)
    lap = a[:-2, 1:-1] + a[2:, 1:-1] + a[1:-1, :-2] + a[1:-1, 2:] - 4 * a[1:-1, 1:-1]
    return float(lap.var())


def edge_map(gray):
    e = np.asarray(gray.filter(ImageFilter.FIND_EDGES))
    binary = e > 40
    return binary, float(binary.mean())


res = {}
for key, name in (("Easy", "image28.jpeg"), ("Hard", "image26.jpeg")):
    small, gray = quarter(name)
    binary, density = edge_map(gray)
    Image.fromarray(np.where(binary, 30, 255).astype("uint8")).save(os.path.join(OUT, f"edges_{key.lower()}.png"))
    small.save(os.path.join(OUT, f"small_{key.lower()}.jpg"), quality=88)
    res["edge" + key] = round(density, 3)

for key, name in (("Night", "image21.jpeg"), ("Day", "image26.jpeg")):
    _, gray = quarter(name)
    mean = float(np.asarray(gray).mean())
    res["gray" + key] = round(mean, 1)
    res["night" + key] = 1 if mean < 80 else 0
    gray.save(os.path.join(OUT, f"gray_{key.lower()}.jpg"), quality=88)

_, gray = quarter("image25.jpeg")
blurred = gray.filter(ImageFilter.GaussianBlur(3))
res["lapSharp"] = round(lap_var(gray))
res["lapBlur"] = round(lap_var(blurred))
res["blurSharp"] = 1 if res["lapSharp"] < 180 else 0
res["blurBlurred"] = 1 if res["lapBlur"] < 180 else 0
gray.save(os.path.join(OUT, "blur_sharp.jpg"), quality=90)
blurred.save(os.path.join(OUT, "blur_blurred.jpg"), quality=90)

with open(os.path.join(ROOT, "assets", "data", "cue_examples.js"), "w") as f:
    f.write("/* Generated by tools/gen_figures.py from the example images. Illustrative only. */\n")
    f.write("window.CUE_EXAMPLES = " + json.dumps(res, indent=1) + ";\n")
print(json.dumps(res))
